# Generated by Django 3.2 on 2021-06-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_mangas_webcomics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='chapter_text',
            field=models.CharField(max_length=200, null='chapitre'),
            preserve_default='chapitre',
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_text',
            field=models.CharField(max_length=200, null='image.jpg'),
            preserve_default='image.jpg',
        ),
        migrations.AddField(
            model_name='item',
            name='link_text',
            field=models.CharField(max_length=200, null='lien'),
            preserve_default='lien',
        ),
        migrations.AddField(
            model_name='item',
            name='title_text',
            field=models.CharField(max_length=200, null='titre'),
            preserve_default='titre',
        ),
    ]
